package http

type PlayerResponse struct {
	ID                  int32  `json:"id"`
	Name                string `json:"name"`
	GroupID             int32  `json:"group_id"`
	AccountID           int32  `json:"account_id"`
	Level               int32  `json:"level"`
	Vocation            int32  `json:"vocation"`
	Health              int32  `json:"health"`
	HealthMax           int32  `json:"health_max"`
	Experience          uint64 `json:"experience"`
	LookBody            int32  `json:"look_body"`
	LookFeet            int32  `json:"look_feet"`
	LookHead            int32  `json:"look_head"`
	LookLegs            int32  `json:"look_legs"`
	LookType            int32  `json:"look_type"`
	LookAddons          int32  `json:"look_addons"`
	MagicLevel          int32  `json:"magic_level"`
	Mana                int32  `json:"mana"`
	ManaMax             int32  `json:"mana_max"`
	ManaSpent           uint64 `json:"mana_spent"`
	Soul                uint32 `json:"soul"`
	TownID              int32  `json:"town_id"`
	PosX                int32  `json:"pos_x"`
	PosY                int32  `json:"pos_y"`
	PosZ                int32  `json:"pos_z"`
	Conditions          []byte `json:"conditions"`
	Cap                 int32  `json:"cap"`
	Sex                 int32  `json:"sex"`
	LastLogin           uint64 `json:"last_login"`
	LastIP              uint32 `json:"last_ip"`
	Save                bool   `json:"save"`
	Skull               int32  `json:"skull"`
	SkullTime           int64  `json:"skull_time"`
	LastLogout          uint64 `json:"last_logout"`
	Blessings           int32  `json:"blessings"`
	OnlineTime          int64  `json:"online_time"`
	Deletion            int64  `json:"deletion"`
	Balance             uint64 `json:"balance"`
	Stamina             uint32 `json:"stamina"`
	SkillFist           uint32 `json:"skill_fist"`
	SkillFistTries      uint64 `json:"skill_fist_tries"`
	SkillClub           uint32 `json:"skill_club"`
	SkillClubTries      uint64 `json:"skill_club_tries"`
	SkillSword          uint32 `json:"skill_sword"`
	SkillSwordTries     uint64 `json:"skill_sword_tries"`
	SkillAxe            uint32 `json:"skill_axe"`
	SkillAxeTries       uint64 `json:"skill_axe_tries"`
	SkillDist           uint32 `json:"skill_dist"`
	SkillDistTries      uint64 `json:"skill_dist_tries"`
	SkillShielding      uint32 `json:"skill_shielding"`
	SkillShieldingTries uint64 `json:"skill_shielding_tries"`
	SkillFishing        uint32 `json:"skill_fishing"`
	SkillFishingTries   uint64 `json:"skill_fishing_tries"`
	Created             int32  `json:"created"`
	Hidden              bool   `json:"hidden"`
	Comment             string `json:"comment"`
}
