package mysql

import (
	"github.com/danilopucci/opentibiagateway/internal/domain"
	"github.com/danilopucci/opentibiagateway/internal/provider/persistence"
)

func PlayerToDomain(entity *persistence.PlayerEntity) *domain.Player {
	return &domain.Player{
		ID:                  int32(entity.ID),
		Name:                entity.Name,
		GroupID:             int32(entity.GroupID),
		AccountID:           int32(entity.AccountID),
		Level:               int32(entity.Level),
		Vocation:            int32(entity.Vocation),
		Health:              int32(entity.Health),
		HealthMax:           int32(entity.HealthMax),
		Experience:          entity.Experience,
		LookBody:            int32(entity.LookBody),
		LookFeet:            int32(entity.LookFeet),
		LookHead:            int32(entity.LookHead),
		LookLegs:            int32(entity.LookLegs),
		LookType:            int32(entity.LookType),
		LookAddons:          int32(entity.LookAddons),
		MagicLevel:          int32(entity.MagLevel),
		Mana:                int32(entity.Mana),
		ManaMax:             int32(entity.ManaMax),
		ManaSpent:           entity.ManaSpent,
		Soul:                uint32(entity.Soul),
		TownID:              int32(entity.TownID),
		PosX:                int32(entity.PosX),
		PosY:                int32(entity.PosY),
		PosZ:                int32(entity.PosZ),
		Conditions:          entity.Conditions,
		Cap:                 int32(entity.Cap),
		Sex:                 int32(entity.Sex),
		LastLogin:           entity.LastLogin,
		LastIP:              uint32(entity.LastIP),
		Save:                entity.Save,
		Skull:               int32(entity.Skull),
		SkullTime:           entity.SkullTime,
		LastLogout:          entity.LastLogout,
		Blessings:           int32(entity.Blessings),
		OnlineTime:          entity.OnlineTime,
		Deletion:            entity.Deletion,
		Balance:             entity.Balance,
		Stamina:             uint32(entity.Stamina),
		SkillFist:           uint32(entity.SkillFist),
		SkillFistTries:      entity.SkillFistTries,
		SkillClub:           uint32(entity.SkillClub),
		SkillClubTries:      entity.SkillClubTries,
		SkillSword:          uint32(entity.SkillSword),
		SkillSwordTries:     entity.SkillSwordTries,
		SkillAxe:            uint32(entity.SkillAxe),
		SkillAxeTries:       entity.SkillAxeTries,
		SkillDistance:       uint32(entity.SkillDist),
		SkillDistanceTries:  entity.SkillDistTries,
		SkillShielding:      uint32(entity.SkillShielding),
		SkillShieldingTries: entity.SkillShieldingTries,
		SkillFishing:        uint32(entity.SkillFishing),
		SkillFishingTries:   entity.SkillFishingTries,
		Created:             int32(entity.Created),
		Hidden:              entity.Hidden,
		Comment:             entity.Comment,
	}
}

func PlayerToEntity(p *domain.Player) *persistence.PlayerEntity {
	return &persistence.PlayerEntity{
		ID:                  int(p.ID),
		Name:                p.Name,
		GroupID:             int(p.GroupID),
		AccountID:           int(p.AccountID),
		Level:               int(p.Level),
		Vocation:            int(p.Vocation),
		Health:              int(p.Health),
		HealthMax:           int(p.HealthMax),
		Experience:          p.Experience,
		LookBody:            int(p.LookBody),
		LookFeet:            int(p.LookFeet),
		LookHead:            int(p.LookHead),
		LookLegs:            int(p.LookLegs),
		LookType:            int(p.LookType),
		LookAddons:          int(p.LookAddons),
		MagLevel:            int(p.MagicLevel),
		Mana:                int(p.Mana),
		ManaMax:             int(p.ManaMax),
		ManaSpent:           p.ManaSpent,
		Soul:                uint(p.Soul),
		TownID:              int(p.TownID),
		PosX:                int(p.PosX),
		PosY:                int(p.PosY),
		PosZ:                int(p.PosZ),
		Conditions:          p.Conditions,
		Cap:                 int(p.Cap),
		Sex:                 int(p.Sex),
		LastLogin:           p.LastLogin,
		LastIP:              uint(p.LastIP),
		Save:                p.Save,
		Skull:               int8(p.Skull),
		SkullTime:           p.SkullTime,
		LastLogout:          p.LastLogout,
		Blessings:           int8(p.Blessings),
		OnlineTime:          p.OnlineTime,
		Deletion:            p.Deletion,
		Balance:             p.Balance,
		Stamina:             uint16(p.Stamina),
		SkillFist:           uint(p.SkillFist),
		SkillFistTries:      p.SkillFistTries,
		SkillClub:           uint(p.SkillClub),
		SkillClubTries:      p.SkillClubTries,
		SkillSword:          uint(p.SkillSword),
		SkillSwordTries:     p.SkillSwordTries,
		SkillAxe:            uint(p.SkillAxe),
		SkillAxeTries:       p.SkillAxeTries,
		SkillDist:           uint(p.SkillDistance),
		SkillDistTries:      p.SkillDistanceTries,
		SkillShielding:      uint(p.SkillShielding),
		SkillShieldingTries: p.SkillShieldingTries,
		SkillFishing:        uint(p.SkillFishing),
		SkillFishingTries:   p.SkillFishingTries,
		Created:             int(p.Created),
		Hidden:              p.Hidden,
		Comment:             p.Comment,
	}
}
