package domain

type Player struct {
	ID                  int32
	Name                string
	GroupID             int32
	AccountID           int32
	Level               int32
	Vocation            int32
	Health              int32
	HealthMax           int32
	Experience          uint64
	LookBody            int32
	LookFeet            int32
	LookHead            int32
	LookLegs            int32
	LookType            int32
	LookAddons          int32
	MagicLevel          int32
	Mana                int32
	ManaMax             int32
	ManaSpent           uint64
	Soul                uint32
	TownID              int32
	PosX                int32
	PosY                int32
	PosZ                int32
	Conditions          []byte
	Cap                 int32
	Sex                 int32
	LastLogin           uint64
	LastIP              uint32
	Save                bool
	Skull               int32
	SkullTime           int64
	LastLogout          uint64
	Blessings           int32
	OnlineTime          int64
	Deletion            int64
	Balance             uint64
	Stamina             uint32
	SkillFist           uint32
	SkillFistTries      uint64
	SkillClub           uint32
	SkillClubTries      uint64
	SkillSword          uint32
	SkillSwordTries     uint64
	SkillAxe            uint32
	SkillAxeTries       uint64
	SkillDistance       uint32
	SkillDistanceTries  uint64
	SkillShielding      uint32
	SkillShieldingTries uint64
	SkillFishing        uint32
	SkillFishingTries   uint64
	Created             int32
	Hidden              bool
	Comment             string
}
